insert into apartment_classes values ('BDRM1', 1, 100);
insert into apartment_classes values ('BDRM2', 2, 150);
insert into apartment_classes values ('Balcony Room', 1, 150);
insert into apartment_classes values ('De Lux1', 1, 250);
insert into apartment_classes values ('De Lux2', 2, 300);
insert into apartment_classes values ('Duplex2', 2, 500);
insert into apartment_classes values ('Duplex4', 4, 750);
insert into apartment_classes values ('Family Room2', 2, 300);
insert into apartment_classes values ('Family Room3', 3, 400);


insert into apartments values ('201', 'BDRM1', 'free');
insert into apartments values ('202', 'BDRM1', 'booked');
insert into apartments values ('203', 'BDRM2', 'booked');
insert into apartments values ('204', 'BDRM2', 'free');
insert into apartments values ('205', 'Balcony Room', 'booked');
insert into apartments values ('206', 'Balcony Room', 'free');
insert into apartments values ('207', 'De Lux1', 'booked');
insert into apartments values ('208', 'De Lux2', 'free');
insert into apartments values ('209', 'Duplex2', 'free');
insert into apartments values ('210', 'Duplex4', 'free');
insert into apartments values ('301', 'BDRM1', 'free');
insert into apartments values ('302', 'BDRM1', 'booked');
insert into apartments values ('303', 'BDRM2', 'booked');
insert into apartments values ('304', 'BDRM2', 'free');
insert into apartments values ('305', 'Balcony Room', 'booked');
insert into apartments values ('306', 'Balcony Room', 'free');
insert into apartments values ('307', 'De Lux1', 'booked');
insert into apartments values ('308', 'De Lux2', 'free');
insert into apartments values ('309', 'Duplex2', 'free');
insert into apartments values ('310', 'Duplex4', 'free');
insert into apartments values ('401', 'BDRM1', 'free');
insert into apartments values ('402', 'BDRM1', 'booked');
insert into apartments values ('403', 'BDRM2', 'booked');
insert into apartments values ('404', 'BDRM2', 'free');
insert into apartments values ('405', 'Balcony Room', 'booked');
insert into apartments values ('406', 'Balcony Room', 'free');
insert into apartments values ('407', 'De Lux1', 'booked');
insert into apartments values ('408', 'De Lux2', 'free');
insert into apartments values ('409', 'Duplex2', 'free');
insert into apartments values ('410', 'Duplex4', 'free');
insert into apartments values ('501', 'BDRM1', 'free');
insert into apartments values ('502', 'BDRM1', 'booked');
insert into apartments values ('503', 'BDRM2', 'booked');
insert into apartments values ('504', 'BDRM2', 'free');
insert into apartments values ('505', 'Balcony Room', 'booked');
insert into apartments values ('506', 'Balcony Room', 'free');
insert into apartments values ('507', 'De Lux1', 'booked');
insert into apartments values ('508', 'De Lux2', 'free');
insert into apartments values ('509', 'Duplex2', 'free');
insert into apartments values ('510', 'Duplex4', 'free');